site_name: Gaia Documentation
site_description: Gaia Documentation
site_author: gaia-app.io

docs_dir: content

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
  logo: assets/gaia_32.png
  favicon: assets/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gaia-app/gaia
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jnURE6h