site_name: Gaia Documentation
site_description: Gaia Documentation
site_author: gaia-app.io

docs_dir: content

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
  logo: assets/gaia_32.png
  favicon: assets/favicon.ico
  font: false
  features:
    - navigation.indexes

nav:
  - index.md
  - Getting started:
    - getting-started/concepts.md
    - getting-started/quick-start.md
  - Configuration:
    - configuration/gaia-configuration.md
    - configuration/database-configuration.md
    - configuration/runner-configuration.md
    - configuration/github-integration.md
  - Credentials:
    - AWS: credentials/aws.md
    - GCP: credentials/gcp.md
    - AzureRM: credentials/azurerm.md
  - about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gaia-app/gaia
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jnURE6h

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
